In [7]:
pip install plotly

Collecting plotly
  Downloading plotly-5.15.0-py2.py3-none-any.whl (15.5 MB)
     --------------------------------------- 15.5/15.5 MB 11.1 MB/s eta 0:00:00
Collecting tenacity>=6.2.0 (from plotly)
  Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
Requirement already satisfied: packaging in c:\users\all\appdata\local\programs\python\python310\lib\site-packages (from plotly) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\all\appdata\local\programs\python\python310\lib\site-packages (from packaging->plotly) (3.0.7)
Installing collected packages: tenacity, plotly
Successfully installed plotly-5.15.0 tenacity-8.2.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Smart_watch_prices.csv')
data

,Brand,Model,Operating System,Connectivity,Display Type,Display Size (inches),Resolution,Water Resistance (meters),Battery Life (days),Heart Rate Monitor,GPS,NFC,Price (USD)
0,Apple,Watch Series 7,watchOS,"Bluetooth, Wi-Fi, Cellular",Retina,1.90,396 x 484,50,18,Yes,Yes,Yes,$399
1,Samsung,Galaxy Watch 4,Wear OS,"Bluetooth, Wi-Fi, Cellular",AMOLED,1.40,450 x 450,50,40,Yes,Yes,Yes,$249
2,Garmin,Venu 2,Garmin OS,"Bluetooth, Wi-Fi",AMOLED,1.30,416 x 416,50,11,Yes,Yes,No,$399
3,Fitbit,Versa 3,Fitbit OS,"Bluetooth, Wi-Fi",AMOLED,1.58,336 x 336,50,6,Yes,Yes,Yes,$229
4,Fossil,Gen 6,Wear OS,"Bluetooth, Wi-Fi",AMOLED,1.28,416 x 416,30,24,Yes,Yes,Yes,$299
...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,Withings,ScanWatch,Withings OS,"Bluetooth, Wi-Fi",PMOLED,1.38,348 x 442,50,30,Yes,No,Yes,$279
375,Zepp,Z,Zepp OS,"Bluetooth, Wi-Fi, Cellular",AMOLED,1.39,454 x 454,50,15,Yes,Yes,Yes,$349
376,Honor,Watch GS Pro,Lite OS,"Bluetooth, Wi-Fi",AMOLED,1.39,454 x 454,50,25,Yes,Yes,Yes,$249
377,Oppo,Watch Free,ColorOS,"Bluetooth, Wi-Fi",AMOLED,1.64,326 x 326,50,14,Yes,No,Yes,$159
378,TicWatch,Pro 3,Wear OS,"Bluetooth, Wi-Fi, Cellular",AMOLED,1.40,454 x 454,50,72,Yes,Yes,Yes,$299

In [3]:
selected_columns = ['Brand', 'Water Resistance (meters)', 'Battery Life (days)', 'Heart Rate Monitor', 'Price (USD)']
data = data[selected_columns]

In [4]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)  # Format float values

print(data)

        Brand Water Resistance (meters) Battery Life (days)  \
0       Apple                        50                  18
1     Samsung                        50                  40
2      Garmin                        50                  11
3      Fitbit                        50                   6
4      Fossil                        30                  24
..        ...                       ...                 ...
374  Withings                        50                  30
375      Zepp                        50                  15
376     Honor                        50                  25
377      Oppo                        50                  14
378  TicWatch                        50                  72

    Heart Rate Monitor Price (USD)
0                  Yes       $399
1                  Yes       $249
2                  Yes       $399
3                  Yes       $229
4                  Yes       $299
..                 ...         ...
374                Yes       $279
375                Yes       $349
376                Yes       $249
377                Yes       $159
378                Yes       $299

[379 rows x 5 columns]

In [5]:
# Print the total number of unique Brands
numOfBrands = len(data['Brand'].unique())
print('Number of categories = ', numOfBrands)

# Count and Print the number of watches in each 'Brand'. 
watchesInEachBrand = data['Brand'].value_counts()
print('Number of watches in each catergory', watchesInEachBrand)

Number of categories =  43
Number of watches in each catergory Garmin            34
Mobvoi            24
Fitbit            24
Fossil            23
Amazfit           20
Samsung           19
Huawei            19
TicWatch          18
Xiaomi            17
Skagen            17
Suunto            16
Honor             14
Apple             14
Polar             12
Casio             10
Withings           9
Oppo               9
Timex              8
Diesel             7
Misfit             7
Michael Kors       6
Zepp               6
LG                 6
TAG Heuer          4
Asus               3
Montblanc          3
Sony               3
Realme             3
Matrix             3
Kate Spade         3
Kospet             2
Emporio Armani     2
Nokia              2
Ticwatch           2
MyKronoz           2
Zeblaze            1
Lemfo              1
Nubia              1
Moto               1
Polaroid           1
Motorola           1
OnePlus            1
Name: Brand, dtype: int64

In [6]:
import plotly
plotly.offline.init_notebook_mode(connected=True)
import plotly.graph_objs as go

# Sort watchesInEachBrand in descending order based on the count of watches in each brand
sorted_watches_in_brand = watchesInEachBrand.sort_values(ascending = False)

dataPlot = [go.Bar(
        x = sorted_watches_in_brand.index, # index = category name
        y = sorted_watches_in_brand.values, # value = count
)]

plotly.offline.iplot(dataPlot)

ModuleNotFoundError: No module named 'plotly'